# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c29795cd4dff218a18d5922b9f24edcd911b79715d9b51735ceb1f77000373ce799f45252deefcb5574c373306ef031226f94d470599829aac299fa195419764

test:
  secret_key_base: 0da55d44983022c996a46bf14868588420dfc017adfb9f131bcc38ab42371bc000b08fa9d020e6af1f1256767d2dcde7e5226fdf90f7418c3a8a4990dc6f8bb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
